@set test=test_add_group.py
@echo Running %test%... 
@pytest --alluredir=allure_results test\%test%
@echo Generating allure reports...
@c:\langTools\allure-2.3.4\bin\allure.bat --clean generate allure_results
